// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCSor9Mfq0gGY_aw8lz-a6qAVpROvJ2pxk',
    appId: '1:1029660015148:web:1332f5db164d496f2c6f89',
    messagingSenderId: '1029660015148',
    projectId: 'eto-rides-7ed89',
    authDomain: 'eto-rides-7ed89.firebaseapp.com',
    storageBucket: 'eto-rides-7ed89.firebasestorage.app',
    measurementId: 'G-S23QDXDMKX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDdYNQqfVAOn6zIDCGaUZ5xbuYx4kVGsqM',
    appId: '1:1029660015148:android:0009f0cb85f33b6c2c6f89',
    messagingSenderId: '1029660015148',
    projectId: 'eto-rides-7ed89',
    storageBucket: 'eto-rides-7ed89.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBQqsjdGs-NeMTpApJ-TKvsW4O-Duw-Vc4',
    appId: '1:1029660015148:ios:97d31fd9e02157ff2c6f89',
    messagingSenderId: '1029660015148',
    projectId: 'eto-rides-7ed89',
    storageBucket: 'eto-rides-7ed89.firebasestorage.app',
    iosBundleId: 'com.example.etoRides',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBQqsjdGs-NeMTpApJ-TKvsW4O-Duw-Vc4',
    appId: '1:1029660015148:ios:97d31fd9e02157ff2c6f89',
    messagingSenderId: '1029660015148',
    projectId: 'eto-rides-7ed89',
    storageBucket: 'eto-rides-7ed89.firebasestorage.app',
    iosBundleId: 'com.example.etoRides',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCSor9Mfq0gGY_aw8lz-a6qAVpROvJ2pxk',
    appId: '1:1029660015148:web:93fc321006b058162c6f89',
    messagingSenderId: '1029660015148',
    projectId: 'eto-rides-7ed89',
    authDomain: 'eto-rides-7ed89.firebaseapp.com',
    storageBucket: 'eto-rides-7ed89.firebasestorage.app',
    measurementId: 'G-P8ZCCS7LTP',
  );
}
